DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS coffee_orders;
CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(40) NOT NULL,
  phone DECIMAL(10) UNIQUE,
  email VARCHAR(255) UNIQUE,
  points INTEGER DEFAULT 5 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS coffee_orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  is_redeemed BOOLEAN DEFAULT FALSE,
  ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  customer_id INTEGER,
  FOREIGN KEY(customer_id) REFERENCES customers(id)
);
